openapi: 3.0.3

info:
  title: Пользователи
  version: 1.0.0

tags:
  - name: Users
    description: Управление пользователями.

paths:
  /api/users/{id}:
    post:
      tags:
        - Users
      operationId: createUser
      summary: Создать пользователя.
      parameters:
        - in: path
          name: id
          description: Идентификатор пользователя.
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Пользователь создан.
        '409':
          description: Пользователь с указанным Id уже существует.
        '500':
          description: Ошибка на стороне сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'

    delete:
      tags:
        - Users
      operationId: deleteUser
      summary: Удалить пользователя.
      parameters:
        - in: path
          name: id
          description: Идентификатор пользователя.
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Пользователь удален.
        '404':
          description: Пользователь с указанным Id не существует.
        '500':
          description: Ошибка на стороне сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'

  

components:
  schemas:
    User:
      $ref: '../DTO/user.schema.json#/definitions/user'
    InternalErrorResponse:
      $ref: '../DTO/internal-error-response.schema.json#/definitions/internalErrorResponse'

